---
# Install required packages

- name: install required packages (debian)
  apt: pkg={{ item }} state=present
  with_items:
    - rabbitmq-server
  when: ansible_os_family == "Debian"

- name: install required packages (EL)
  yum: pkg={{ item }} state=present
  with_items:
    - erlang
  when: ansible_os_family == "RedHat"

- name: Ensure RabbitMQ is installed
  yum:
    name=http://www.rabbitmq.com/releases/rabbitmq-server/v3.3.5/rabbitmq-server-3.3.5-1.noarch.rpm
    state=present
  when: ansible_os_family == "RedHat"